###
POST http://localhost:3001/wallet/update/exchange
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGUyMjhkYzE2Yzc1MTBkY2MwYmI4YzciLCJpYXQiOjE2MjU0MzQ2MTEsImV4cCI6MTYyNTQ1NjIxMX0.24J704BCo8ckotL8tC0EvlgzoOMqGjcCtNsXNMAACfA

{
  "currency_from": "Ethereum",
  "currency_to": "Bitcoin",
  "amount": 20
}